### ISSUE TITLE
Compilation in Delphi Tokyo gives error

### ISSUE THREAD

**Issue by kStarbe** [rzaripov1990/ModernListView#12]
[dcc32 Fatal Error] FMX.ListView.pas(21): F2051 Unit FMX.ListView.Adapters.Base was compiled with a different version of FMX.ListView.Types.TListItem

Sorry just saw the Tokyo version ...

**Comment by rzaripov1990** [comment]
Hi, check Tokyo path in repository

**Comment by kStarbe** [comment]
Found out that there are 2 versions. I adapted the file set and it is ok.
Thanks.
