### ISSUE TITLE
demo ‘parameters’  can’t the effect on windows or mac

### ISSUE THREAD

**Issue by jonahzheng** [rzaripov1990/ModernListView#3]
demo ‘parameters’  can’t the effect on windows or mac。

**Comment by rzaripov1990** [comment]
what do you mean?

**Comment by jonahzheng** [comment]
![2222](https://cloud.githubusercontent.com/assets/5125282/19302906/fd21494a-9098-11e6-8a86-9bb011ba0615.png)

ListView1.getAniCalc.BoundsAnimation := false;
this code can't run

**Comment by rzaripov1990** [comment]
need to check
if ListView1.getAniCalc <> nil then

**Comment by jonahzheng** [comment]
yes, i know ListView1.getAniCalc is nil in windows or mac.
//===================
procedure TForm4.ListView1Paint(Sender: TObject; Canvas: TCanvas;
  const ARect: TRectF);
begin
  Text1.Text := string.Join(':', [ListView1.getFirstVisibleItemIndex,
    ListView1.getVisibleCount, ListView1.getLastVisibleItemindex]);
  inc(Counter);
  Caption := Counter.ToString;
end;
//====================
but ListView1.getFirstVisibleItemIndex and ListView1.getLastVisibleItemindex can't get value in windows and mac. always 0 and 9.

**Comment by rzaripov1990** [comment]
use OnScrollViewChange event
```
procedure TForm4.ListView1ScrollViewChange(Sender: TObject);
begin
  Text1.Text := string.Join(':', [ListView1.getFirstVisibleItemIndex, ListView1.getVisibleCount,
    ListView1.getLastVisibleItemindex]);
end;
```
