### ISSUE TITLE
ModernListView supported multiselect that it like listbox's multiselect

### ISSUE THREAD

**Issue by jonahzheng** [rzaripov1990/ModernListView#5]
like this,
![Image of Yaktocat](https://cloud.githubusercontent.com/assets/5125282/12077295/24cd7c30-b218-11e5-9fa5-d58ed8d028ae.png)

thank you very much!

**Comment by rzaripov1990** [comment]
it's very easy
https://github.com/rzaripov1990/blog_demo/tree/master/ModernLV_MultiSelect

**Comment by jonahzheng** [comment]
wow! cool! thank you.
