### ISSUE TITLE
uForm3.pas (Column Mode) : OnPaint used instead of OnPainting

### ISSUE THREAD

**Issue by ChloeDigitalTechnologies** [rzaripov1990/ModernListView#8]
Must use "OnPainting" event (TForm3.ListView1Painting) instead of OnPaint event (TForm3.ListView1Paint);
It refreshes the painting of the bitmaps a lot better !

OnPainting is triggered before OnPaint. OnPainting 
signals that the control is about to be drawn, in case the rendering conditions 
need to be customized beforehand. OnPaint does the actual drawing.

Therefore, loading the bitmaps should be done before the on paint event, in order to be handled by the Listview.DoPaint method, or you are obliged to render them in onpaint with iBitmap.Render(Canvas,etc..)

Many thanks for this nice ModernListview you have created.

**Comment by rzaripov1990** [comment]
I do not remember details why I chose the OnPaint event, but this is demo-project. I don't insist on correct implementation.
As will be time, I will check the variant offered by you, but now I will close the question.

Thank you! If there are ideas or improvements, do not hesitate to do Pull-Request or Issues

**Comment by ChloeDigitalTechnologies** [comment]
Of course I will 👍 

In fact I am working for myself about a "small and simple" media center in order to display my video movie files with their Posters and Title. See Screenshot with Modern Listview in action :)

![mymediacenter](https://user-images.githubusercontent.com/17040319/28092720-c24985d0-6694-11e7-91c4-c2acb754bbd6.png)

**Comment by rzaripov1990** [comment]
It's cool! 
If you donate a demo-project, I will post it

Thanks
